### ISSUE TITLE
Incorrect/inconsistent values because of the async method

### ISSUE THREAD

**Issue by renatosuero** [filhodanuvem/polyglot#12]
if you to run 2x the same user you will have different result. I was checking and in my user I start 8 goroutines [here](https://github.com/filhodanuvem/polyglot/blob/master/stats/stats.go#L22) to process the repos but only 4 is processed [here](https://github.com/filhodanuvem/polyglot/blob/master/stats/stats.go#L49)

![Screenshot 2021-02-12 at 13 56 23](https://user-images.githubusercontent.com/1093214/107770693-1b63fb00-6d3a-11eb-9445-ab9d8508e00e.png)

I've changed the code and now it looks ok, you can see here:
![Screenshot 2021-02-12 at 14 00 21](https://user-images.githubusercontent.com/1093214/107771151-a93fe600-6d3a-11eb-859e-da49af4848ef.png)

I'd like to write tests but because of [this function](https://github.com/filhodanuvem/polyglot/blob/master/stats/stats.go#L76), it do a lot of things and I don't see a way to do that without change the code otherwise the test will have to create the files and add a validation to avoid download if the folder is available for example, I'd like to know what do you think @filhodanuvem 

PS. I didn't create a PR, because maybe I'm missing something and the change isn't necessary

**Comment by filhodanuvem** [comment]
Great job @renatosuero, not sure if it was a huge change but please send the PR. I've noticed that the result was different in the past but I thought it was because of the limit of repos that polyglot analyses somehow. So for sure there is a bug here.
