### ISSUE TITLE
API 

### ISSUE THREAD

**Issue by filhodanuvem** [filhodanuvem/polyglot#2]
We should be able to run `polyglot --server` to start an api that returns the same json as in the cli version. 

**Request**
`http://localhost:3001/user=filhodanuvem&limit=2` 

**Response**
```
{
    "languages" : [
         "PHP"
         "Go"
     ]
}
```

**Comment by victorabarros** [comment]
[on going](https://github.com/victorabarros/polyglot/tree/feature/server)
