### ISSUE TITLE
Support to other providers (Gitlab)

### ISSUE THREAD

**Issue by filhodanuvem** [filhodanuvem/polyglot#3]
Make possible  to download repositories from other providers rather than github. 
**Example**
```bash
polyglot --username=filhodanuvem --provider=gitlab
```

**Comment by EnzoBtv** [comment]
Hey @filhodanuvem! Can I get this Issue?

**Comment by EnzoBtv** [comment]
I've done it already, I'm open to any comments or improvements

If you could mark it as hacktoberfest-accepted I would be happy :)

**Comment by filhodanuvem** [comment]
Closing this with #9
